### PR TITLE
Branch tutorial

### PR DESCRIPTION
**Pull request by audhalbritter**
I have added a tutorial on how to make forks and branches. No pictures commited yet, because they are large...

### CODE REVIEW

**Review by richardjtelford — COMMENTED** [review]
I don't think you need to commit the html. Good start. Need to think about what else we need to include for git. I'm thinking
* Why Version Control
* Make a github account and install git
* Working with a new project (make repo, make new rstudio project)
* Working with an existing project (make repo, clone to project)
* Committing, push and pull
* Undoing last commit
* .gitignore

**Comment by richardjtelford** [comment]
Videos would be excellent for some of this

**Comment by audhalbritter** [comment]
I was thinking to have another tutorial on connect git, github, rstudio, clone repo, commit, push, pull. That would be the first one.
And yes videos would be good!

**Comment by audhalbritter** [comment]
I was thinking to have another tutorial on connect git, github, rstudio, clone repo, commit, push, pull. That would be the first one.
And yes videos would be good!

**Pull request merged**
