### PR TITLE
Adding simple-linear-regression.Rmd page

### PR DESCRIPTION
**Pull request by emilygsimmonds**
I have been working on the second draft of the simple linear regression page and wanted to try out a pull request. 

I have tried to convert everything into the tone desired and the most recent template. I hope this is ok.

I am not sure that the biostats_theme for the plots is working!

### CODE REVIEW

**Comment by audhalbritter** [comment]
Hi Emily, this looks great. I've only had a quick look at it, but I think this is soon ready to go online.
I made a change to the biostats theme file and how to use it in the template. Basically, you just have to source the theme file and then each figure should have the right theme. So no need to add the theme to the figures. It did not work before, sorry for that. But now it is fixed.
Richard is also looking through this and he had a few minor comments I think.
I'll have a proper look soon, when I have a bit more time.

**Comment by emilygsimmonds** [comment]
Thank you Aud. Will the comments from yourself and Richard appear here with a notification for me? Or should I look elsewhere? I haven't used comments on pull requests before. 

Also, should I update the theme part of the figures now or wait until after comments?

**Comment by audhalbritter** [comment]
we will comment directly in your commits, but you will get a notification.
You also managed to push from main instead of from your branch and you have deleted your branch. Richard can maybe help you with this, but it would be good if you try to make the pull request from the branch. Otherwise it will be a mess when you fetch the changes from upstream. Because you have then changed main. But ask if it is unclear.
Try and fix the branch thing first. Then you can start fixing things and push and it will automatically add to the pull request. If you stay on the same branch. I tend to keep the branch until I have fixed one problem. And then switch to the next branch.

**Comment by emilygsimmonds** [comment]
Ok, so would you prefer me to re-open the branch and send another pull request from there or will it all be linked?

**Comment by audhalbritter** [comment]
Yes, that would be best, otherwise there will be merge conflicts later. And that's best avoided.

**Comment by emilygsimmonds** [comment]
I was checking your tutorial on branches again and it says to push your branch back to your main before sending the pull request. Which is what I did before but I guess the error was to then delete the branch. I have now recreated it. Would it still be better to send the pull request from the branch? Or does that step have to go through main (this latter one is my current understanding from the tutorial)?

**Comment by audhalbritter** [comment]
Ok, this might be a mistake in my tutorial then! sorry, I will check. I have not had the final check on this with richard yet... the workflow is to push the branch to your remote and then make the pull request from the branch. And you can only delete the branch once it has been accepted, otherwise the pull request is also deleted. But I did that mistake also the first time, because I wanted to have my repo clean...

**Pull request closed without merging**
